### PR TITLE
re-work of the index.md file

### PR DESCRIPTION
**Pull request by kingman**
@gguuss
Hi Gus,
I have now added most of the content from the original post to the index.md file. 
Please review the the content and feel free to edit, add and remove.

I will now start look into the stackdriver part which I and Preston discussed.

Best,
Charlie

### CODE REVIEW

**Review by gguuss — APPROVED** [review]
LGTM, thank you for putting this together!

**Comment by kingman** [comment]
@gguuss 
do you have the right to merge this to master?

**Comment by gguuss** [comment]
I don't have merge permissions, @jmdobry does and would need to process the change to publish the article.

**Comment by jmdobry** [comment]
I don't see a PR to the main GoogleCloudPlatform/community repo?

**Comment by gguuss** [comment]
@kingman I didn't realize this was a fork of the fork, I was able to commit directly into tyagihas:master after cloning it, which updates the PR on the GoogleCloudPlatform/community repo. You can either remake the PR from your fork or can commit the changes directly into the PR by committing to tyagihas fork.

**Comment by kingman** [comment]
@tyagihas 
Hi Teppei,
could you give me write access right to your forked community repos so I can commit some changes I made to the iot-rtdp index.md file.
Best,
Charlie

**Pull request merged**
